//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQA_Core.OQAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OQAService.IOQAContract")]
    public interface IOQAContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpInfo", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpInfoResponse")]
        WCFModels.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp> QueryEmpInfo(WCFModels.Message.QueryEmpReq queryEmpReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpInfo", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpInfoResponse")]
        System.Threading.Tasks.Task<WCFModels.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp>> QueryEmpInfoAsync(WCFModels.Message.QueryEmpReq queryEmpReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpPercent", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpPercentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.PageQueryReq))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView> QueryEmpPercent(WCFModels.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpPercent", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpPercentResponse")]
        System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView>> QueryEmpPercentAsync(WCFModels.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpSum", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpSumResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.PageQueryReq))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView> QueryEmpSum(WCFModels.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/QueryEmpSum", ReplyAction="http://tempuri.org/IOQAContract/QueryEmpSumResponse")]
        System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView>> QueryEmpSumAsync(WCFModels.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/UpdateEmpInfo", ReplyAction="http://tempuri.org/IOQAContract/UpdateEmpInfoResponse")]
        WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp> UpdateEmpInfo(WCFModels.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/UpdateEmpInfo", ReplyAction="http://tempuri.org/IOQAContract/UpdateEmpInfoResponse")]
        System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp>> UpdateEmpInfoAsync(WCFModels.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/UpdateDemoInfo", ReplyAction="http://tempuri.org/IOQAContract/UpdateDemoInfoResponse")]
        WCFModels.Message.ModelRsp<WCFModels.Message.DemoView> UpdateDemoInfo(WCFModels.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOQAContract/UpdateDemoInfo", ReplyAction="http://tempuri.org/IOQAContract/UpdateDemoInfoResponse")]
        System.Threading.Tasks.Task<WCFModels.Message.ModelRsp<WCFModels.Message.DemoView>> UpdateDemoInfoAsync(WCFModels.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOQAContractChannel : OQA_Core.OQAService.IOQAContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OQAContractClient : System.ServiceModel.ClientBase<OQA_Core.OQAService.IOQAContract>, OQA_Core.OQAService.IOQAContract {
        
        public OQAContractClient() {
        }
        
        public OQAContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OQAContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OQAContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OQAContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFModels.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp> QueryEmpInfo(WCFModels.Message.QueryEmpReq queryEmpReq) {
            return base.Channel.QueryEmpInfo(queryEmpReq);
        }
        
        public System.Threading.Tasks.Task<WCFModels.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp>> QueryEmpInfoAsync(WCFModels.Message.QueryEmpReq queryEmpReq) {
            return base.Channel.QueryEmpInfoAsync(queryEmpReq);
        }
        
        public WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView> QueryEmpPercent(WCFModels.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpPercent(queryReq);
        }
        
        public System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView>> QueryEmpPercentAsync(WCFModels.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpPercentAsync(queryReq);
        }
        
        public WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView> QueryEmpSum(WCFModels.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpSum(queryReq);
        }
        
        public System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView>> QueryEmpSumAsync(WCFModels.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpSumAsync(queryReq);
        }
        
        public WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp> UpdateEmpInfo(WCFModels.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq) {
            return base.Channel.UpdateEmpInfo(updateReq);
        }
        
        public System.Threading.Tasks.Task<WCFModels.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp>> UpdateEmpInfoAsync(WCFModels.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq) {
            return base.Channel.UpdateEmpInfoAsync(updateReq);
        }
        
        public WCFModels.Message.ModelRsp<WCFModels.Message.DemoView> UpdateDemoInfo(WCFModels.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq) {
            return base.Channel.UpdateDemoInfo(updateReq);
        }
        
        public System.Threading.Tasks.Task<WCFModels.Message.ModelRsp<WCFModels.Message.DemoView>> UpdateDemoInfoAsync(WCFModels.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq) {
            return base.Channel.UpdateDemoInfoAsync(updateReq);
        }
    }
}
