//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.WcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IWcfContract")]
    public interface IWcfContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/Login", ReplyAction="http://tempuri.org/IWcfContract/LoginResponse")]
        Models.Message.ModelListRsp<string> Login(WCFModels.Message.LoginReq loginReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/Login", ReplyAction="http://tempuri.org/IWcfContract/LoginResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelListRsp<string>> LoginAsync(WCFModels.Message.LoginReq loginReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/QueryControlAccessStringResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Models.Message.PageQueryReq))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.ControlAccessString> QueryControlAccessString(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/QueryControlAccessStringResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> QueryControlAccessStringAsync(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/PageQueryControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/PageQueryControlAccessStringResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString> PageQueryControlAccessString(Models.Message.PageQueryReq pageQueryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/PageQueryControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/PageQueryControlAccessStringResponse")]
        System.Threading.Tasks.Task<Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> PageQueryControlAccessStringAsync(Models.Message.PageQueryReq pageQueryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/UpdateControlAccessStringResponse")]
        Models.Message.ModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString> UpdateControlAccessString(Models.Message.UpdateModelReq<WCFModels.MESDB.FWTST1.ControlAccessString> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateControlAccessString", ReplyAction="http://tempuri.org/IWcfContract/UpdateControlAccessStringResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> UpdateControlAccessStringAsync(Models.Message.UpdateModelReq<WCFModels.MESDB.FWTST1.ControlAccessString> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpInfo", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpInfoResponse")]
        Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp> QueryEmpInfo(WCFModels.Message.QueryEmpReq queryEmpReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpInfo", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpInfoResponse")]
        System.Threading.Tasks.Task<Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp>> QueryEmpInfoAsync(WCFModels.Message.QueryEmpReq queryEmpReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpPercent", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpPercentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Models.Message.PageQueryReq))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView> QueryEmpPercent(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpPercent", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpPercentResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView>> QueryEmpPercentAsync(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpSum", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpSumResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Models.Message.PageQueryReq))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFModels.Message.QueryEmpReq))]
        Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView> QueryEmpSum(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/QueryEmpSum", ReplyAction="http://tempuri.org/IWcfContract/QueryEmpSumResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView>> QueryEmpSumAsync(Models.Message.QueryReq queryReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateEmpInfo", ReplyAction="http://tempuri.org/IWcfContract/UpdateEmpInfoResponse")]
        Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp> UpdateEmpInfo(Models.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateEmpInfo", ReplyAction="http://tempuri.org/IWcfContract/UpdateEmpInfoResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp>> UpdateEmpInfoAsync(Models.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateDemoInfo", ReplyAction="http://tempuri.org/IWcfContract/UpdateDemoInfoResponse")]
        Models.Message.ModelRsp<WCFModels.Message.DemoView> UpdateDemoInfo(Models.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfContract/UpdateDemoInfo", ReplyAction="http://tempuri.org/IWcfContract/UpdateDemoInfoResponse")]
        System.Threading.Tasks.Task<Models.Message.ModelRsp<WCFModels.Message.DemoView>> UpdateDemoInfoAsync(Models.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfContractChannel : WcfClient.WcfService.IWcfContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfContractClient : System.ServiceModel.ClientBase<WcfClient.WcfService.IWcfContract>, WcfClient.WcfService.IWcfContract {
        
        public WcfContractClient() {
        }
        
        public WcfContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Models.Message.ModelListRsp<string> Login(WCFModels.Message.LoginReq loginReq) {
            return base.Channel.Login(loginReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelListRsp<string>> LoginAsync(WCFModels.Message.LoginReq loginReq) {
            return base.Channel.LoginAsync(loginReq);
        }
        
        public Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.ControlAccessString> QueryControlAccessString(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryControlAccessString(queryReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> QueryControlAccessStringAsync(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryControlAccessStringAsync(queryReq);
        }
        
        public Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString> PageQueryControlAccessString(Models.Message.PageQueryReq pageQueryReq) {
            return base.Channel.PageQueryControlAccessString(pageQueryReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> PageQueryControlAccessStringAsync(Models.Message.PageQueryReq pageQueryReq) {
            return base.Channel.PageQueryControlAccessStringAsync(pageQueryReq);
        }
        
        public Models.Message.ModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString> UpdateControlAccessString(Models.Message.UpdateModelReq<WCFModels.MESDB.FWTST1.ControlAccessString> updateReq) {
            return base.Channel.UpdateControlAccessString(updateReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelRsp<WCFModels.MESDB.FWTST1.ControlAccessString>> UpdateControlAccessStringAsync(Models.Message.UpdateModelReq<WCFModels.MESDB.FWTST1.ControlAccessString> updateReq) {
            return base.Channel.UpdateControlAccessStringAsync(updateReq);
        }
        
        public Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp> QueryEmpInfo(WCFModels.Message.QueryEmpReq queryEmpReq) {
            return base.Channel.QueryEmpInfo(queryEmpReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.PageModelRsp<WCFModels.MESDB.FWTST1.Emp>> QueryEmpInfoAsync(WCFModels.Message.QueryEmpReq queryEmpReq) {
            return base.Channel.QueryEmpInfoAsync(queryEmpReq);
        }
        
        public Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView> QueryEmpPercent(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpPercent(queryReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpPercentView>> QueryEmpPercentAsync(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpPercentAsync(queryReq);
        }
        
        public Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView> QueryEmpSum(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpSum(queryReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.CEmpSumView>> QueryEmpSumAsync(Models.Message.QueryReq queryReq) {
            return base.Channel.QueryEmpSumAsync(queryReq);
        }
        
        public Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp> UpdateEmpInfo(Models.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq) {
            return base.Channel.UpdateEmpInfo(updateReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelListRsp<WCFModels.MESDB.FWTST1.Emp>> UpdateEmpInfoAsync(Models.Message.UpdateModelListReq<WCFModels.MESDB.FWTST1.Emp> updateReq) {
            return base.Channel.UpdateEmpInfoAsync(updateReq);
        }
        
        public Models.Message.ModelRsp<WCFModels.Message.DemoView> UpdateDemoInfo(Models.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq) {
            return base.Channel.UpdateDemoInfo(updateReq);
        }
        
        public System.Threading.Tasks.Task<Models.Message.ModelRsp<WCFModels.Message.DemoView>> UpdateDemoInfoAsync(Models.Message.UpdateModelReq<WCFModels.Message.DemoView> updateReq) {
            return base.Channel.UpdateDemoInfoAsync(updateReq);
        }
    }
}
